# Generated by Django 5.0.4 on 2024-04-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('command_line', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('commands', models.ManyToManyField(to='serverpanel.command')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ram', models.IntegerField()),
                ('storage_amount', models.IntegerField()),
                ('start_command', models.CharField(max_length=255)),
                ('stop_command', models.CharField(max_length=255)),
                ('configuration', models.ManyToManyField(to='serverpanel.configuration')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverpanel.game')),
                ('owner', models.ManyToManyField(to='accounts.paneluser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(to='accounts.paneluser')),
            ],
        ),
    ]
