# Generated by Django 5.0.4 on 2024-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
