# Generated by Django 5.0.4 on 2024-04-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0002_command_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='value',
        ),
    ]
