# Generated by Django 5.0.4 on 2024-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('serverpanel', '0003_remove_user_rank_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create', models.BooleanField()),
                ('read', models.BooleanField()),
                ('update', models.BooleanField()),
                ('delete', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='permission',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
