# Generated by Django 5.0.4 on 2024-04-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0004_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='directory',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
