# Generated by Django 5.0.4 on 2024-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0005_server_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='command',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_line',
            field=models.CharField(default='', max_length=255),
        ),
    ]
