# Generated by Django 5.0.4 on 2024-04-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
