# Generated by Django 5.0.4 on 2024-04-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0006_command_command_type_command_link_server_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='configuration',
        ),
        migrations.AddField(
            model_name='server',
            name='configuration',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverpanel.configuration'),
        ),
    ]
