# Generated by Django 5.0.4 on 2024-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0008_remove_server_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
