# Generated by Django 5.0.4 on 2024-04-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('serverpanel', '0008_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='permissions',
            field=models.ManyToManyField(related_name='ranks_permissions', to='auth.group'),
        ),
    ]
