# Generated by Django 5.0.4 on 2024-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0009_command_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='file_name',
            field=models.CharField(default='server.jar', max_length=255),
        ),
    ]
