# Generated by Django 5.0.4 on 2024-04-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0010_alter_command_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='max_ram',
        ),
        migrations.RemoveField(
            model_name='server',
            name='storage_amount',
        ),
    ]
