# Generated by Django 5.0.4 on 2024-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0011_remove_server_max_ram_remove_server_storage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='max_ram',
            field=models.IntegerField(default=2),
        ),
    ]
