# Generated by Django 5.0.4 on 2024-04-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0012_server_max_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stop_command',
            field=models.CharField(default='stop', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='stop_type',
            field=models.CharField(default='OS_COMMAND - PROGRAM_COMMAND', max_length=255),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_line',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='command',
            name='file_name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='command',
            name='link',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
