# Generated by Django 5.0.4 on 2024-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0013_rank_remove_command_server_remove_paneluser_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneluser',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
