# Generated by Django 5.0.4 on 2024-04-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0013_game_stop_command_game_stop_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='start_command',
        ),
        migrations.RemoveField(
            model_name='server',
            name='stop_command',
        ),
    ]
