# Generated by Django 5.0.4 on 2024-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('serverpanel', '0014_paneluser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='permission',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
