# Generated by Django 5.0.4 on 2024-04-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0014_remove_server_start_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='start_command',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_command', to='serverpanel.command'),
        ),
        migrations.AddField(
            model_name='server',
            name='stop_command',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_command', to='serverpanel.command'),
        ),
    ]
