# Generated by Django 5.0.4 on 2024-04-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0016_paneluser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneluser',
            name='username',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
