# Generated by Django 5.0.4 on 2024-04-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0017_alter_paneluser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paneluser',
            name='last_login',
        ),
    ]
