# Generated by Django 5.0.4 on 2024-05-01 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0017_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serverpanel.port'),
        ),
    ]
