# Generated by Django 5.0.4 on 2024-05-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0018_alter_server_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='port',
        ),
    ]
