# Generated by Django 5.0.4 on 2024-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('serverpanel', '0018_remove_paneluser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ManyToManyField(to='accounts.paneluser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ManyToManyField(to='accounts.paneluser'),
        ),
        migrations.DeleteModel(
            name='PanelUser',
        ),
    ]
