# Generated by Django 5.0.4 on 2024-05-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0019_remove_server_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.ManyToManyField(to='serverpanel.port'),
        ),
    ]
