# Generated by Django 5.0.4 on 2024-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0020_server_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='name',
            field=models.CharField(default='default-port', max_length=255),
        ),
    ]
