# Generated by Django 5.0.4 on 2024-05-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0021_port_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='port',
        ),
        migrations.AddField(
            model_name='port',
            name='server',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverpanel.server'),
        ),
    ]
