# Generated by Django 5.0.4 on 2024-05-01 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0023_remove_port_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='server',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='serverpanel.server'),
        ),
    ]
