# Generated by Django 5.0.4 on 2024-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0024_port_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='server',
        ),
        migrations.AddField(
            model_name='port',
            name='server',
            field=models.ManyToManyField(null=True, to='serverpanel.server'),
        ),
    ]
