# Generated by Django 5.0.4 on 2024-05-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0029_remove_port_server'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Port',
            new_name='Parameters',
        ),
        migrations.AddField(
            model_name='server',
            name='parameters',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverpanel.parameters'),
        ),
    ]
