# Generated by Django 5.0.4 on 2024-05-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0030_rename_port_parameters_server_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='parameters',
        ),
        migrations.AddField(
            model_name='server',
            name='parameters',
            field=models.ManyToManyField(to='serverpanel.parameters'),
        ),
    ]
