# Generated by Django 5.0.4 on 2024-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0031_remove_server_parameters_server_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='delay',
            field=models.IntegerField(default=0),
        ),
    ]
