# Generated by Django 5.0.4 on 2024-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpanel', '0032_command_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sub_directory',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
