# Generated by Django 5.0.4 on 2024-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serverpanel', '0018_remove_paneluser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255, unique=True)),
                ('email', models.EmailField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('server_count', models.IntegerField(default=0)),
                ('rank', models.ManyToManyField(to='serverpanel.rank')),
            ],
        ),
    ]
