# Generated by Django 5.0.4 on 2024-04-27 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_paneluser_options_alter_paneluser_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paneluser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='username',
        ),
        migrations.AddField(
            model_name='paneluser',
            name='user_ptr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='paneluser', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
