# Generated by Django 5.0.4 on 2024-04-27 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_paneluser_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paneluser',
            name='rank',
        ),
        migrations.AddField(
            model_name='paneluser',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rank'),
        ),
    ]
